# Generated by Django 3.1.7 on 2021-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_auto_20210321_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
