# Generated by Django 3.1.7 on 2021-03-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20210321_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
    ]
