# Generated by Django 3.1.2 on 2021-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20210321_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='field',
            field=models.CharField(default='', max_length=300),
        ),
    ]
