# Generated by Django 3.1.2 on 2021-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_doctor_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='field',
            field=models.CharField(max_length=300),
        ),
    ]
